
import FooterUI from "../../components/footer";
import NavBarUI from "../../components/Navbar";
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavBarUI/>
        <main className="relative overflow-hidden">
          {children}
        </main>
        <FooterUI/>
      </body>
    </html>
  );
}